/**
 * Données statiques marques / modèles pour le formulaire de déclaration véhicule.
 * Couvre les marques les plus courantes en Afrique de l'Ouest, France et diaspora.
 */

export type CarMake = {
  name: string;
  models: string[];
};

export const CAR_DATA: CarMake[] = [
  {
    name: "Toyota",
    models: [
      "Auris",
      "Avensis",
      "C-HR",
      "Camry",
      "Corolla",
      "Fortuner",
      "HiAce",
      "Highlander",
      "Hilux",
      "Land Cruiser",
      "Land Cruiser Prado",
      "Prius",
      "RAV4",
      "Rush",
      "Sequoia",
      "Starlet",
      "Surf",
      "Urban Cruiser",
      "Vitz",
      "Yaris",
    ],
  },
  {
    name: "Nissan",
    models: [
      "Almera",
      "Armada",
      "Frontier",
      "Juke",
      "Leaf",
      "Maxima",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "Pathfinder",
      "Patrol",
      "Pickup",
      "Qashqai",
      "Rogue",
      "Sunny",
      "Terrano",
      "Tiida",
      "X-Trail",
    ],
  },
  {
    name: "Honda",
    models: [
      "Accord",
      "City",
      "Civic",
      "CR-V",
      "CR-Z",
      "Element",
      "Fit",
      "HR-V",
      "Jazz",
      "Legend",
      "Odyssey",
      "Passport",
      "Pilot",
      "Ridgeline",
    ],
  },
  {
    name: "Hyundai",
    models: [
      "Accent",
      "Azera",
      "Creta",
      "Elantra",
      "Genesis",
      "Getz",
      "Grand i10",
      "i10",
      "i20",
      "i30",
      "i40",
      "Ioniq",
      "Matrix",
      "Santa Fe",
      "Sonata",
      "Starex",
      "Terracan",
      "Tucson",
      "Veloster",
    ],
  },
  {
    name: "Kia",
    models: [
      "Carens",
      "Carnival",
      "Ceed",
      "EV6",
      "Niro",
      "Optima",
      "Picanto",
      "Rio",
      "Seltos",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "Telluride",
    ],
  },
  {
    name: "Mitsubishi",
    models: [
      "ASX",
      "Eclipse Cross",
      "Galant",
      "L200",
      "L300",
      "Lancer",
      "Montero",
      "Outlander",
      "Pajero",
      "Pajero Sport",
      "Space Star",
    ],
  },
  {
    name: "Peugeot",
    models: [
      "1007",
      "107",
      "108",
      "2008",
      "206",
      "207",
      "208",
      "3008",
      "301",
      "306",
      "307",
      "308",
      "4007",
      "4008",
      "406",
      "407",
      "5008",
      "508",
      "Partner",
      "Rifter",
    ],
  },
  {
    name: "Renault",
    models: [
      "Captur",
      "Clio",
      "Duster",
      "Espace",
      "Fluence",
      "Kadjar",
      "Kangoo",
      "Koleos",
      "Laguna",
      "Logan",
      "Master",
      "Mégane",
      "Modus",
      "Sandero",
      "Scenic",
      "Symbol",
      "Talisman",
      "Trafic",
      "Twingo",
      "Zoe",
    ],
  },
  {
    name: "Citroën",
    models: [
      "Berlingo",
      "C-Crosser",
      "C-Elysée",
      "C1",
      "C2",
      "C3",
      "C3 Aircross",
      "C4",
      "C4 Picasso",
      "C5",
      "C5 Aircross",
      "C8",
      "Dispatch",
      "DS3",
      "DS4",
      "DS5",
      "Jumper",
      "Jumpy",
      "Nemo",
      "Saxo",
    ],
  },
  {
    name: "Volkswagen",
    models: [
      "Amarok",
      "Caddy",
      "Golf",
      "Golf Plus",
      "Jetta",
      "Multivan",
      "Passat",
      "Phaeton",
      "Polo",
      "Scirocco",
      "Sharan",
      "Tiguan",
      "Touareg",
      "Touran",
      "Transporter",
      "Up",
    ],
  },
  {
    name: "Ford",
    models: [
      "B-Max",
      "C-Max",
      "EcoSport",
      "Edge",
      "Escape",
      "Everest",
      "Explorer",
      "F-150",
      "Fiesta",
      "Focus",
      "Fusion",
      "Galaxy",
      "Grand C-Max",
      "Kuga",
      "Mondeo",
      "Mustang",
      "Ranger",
      "S-Max",
      "Transit",
    ],
  },
  {
    name: "Mercedes-Benz",
    models: [
      "Classe A",
      "Classe B",
      "Classe C",
      "Classe E",
      "Classe G",
      "Classe GL",
      "Classe GLA",
      "Classe GLC",
      "Classe GLE",
      "Classe GLK",
      "Classe M",
      "Classe ML",
      "Classe S",
      "Sprinter",
      "Viano",
      "Vito",
    ],
  },
  {
    name: "BMW",
    models: [
      "Série 1",
      "Série 2",
      "Série 3",
      "Série 4",
      "Série 5",
      "Série 6",
      "Série 7",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
    ],
  },
  {
    name: "Audi",
    models: [
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "TT",
    ],
  },
  {
    name: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  },
  {
    name: "Jeep",
    models: [
      "Cherokee",
      "Commander",
      "Compass",
      "Grand Cherokee",
      "Patriot",
      "Renegade",
      "Wrangler",
    ],
  },
  {
    name: "Chevrolet",
    models: [
      "Aveo",
      "Blazer",
      "Camaro",
      "Captiva",
      "Colorado",
      "Cruze",
      "Epica",
      "Equinox",
      "Lacetti",
      "Malibu",
      "Matiz",
      "Niva",
      "Orlando",
      "Silverado",
      "Spark",
      "Suburban",
      "Tahoe",
      "Trailblazer",
      "Trax",
    ],
  },
  {
    name: "Dacia",
    models: [
      "Dokker",
      "Duster",
      "Jogger",
      "Lodgy",
      "Logan",
      "MCV",
      "Sandero",
      "Spring",
    ],
  },
  {
    name: "Isuzu",
    models: ["D-Max", "MU-X", "MU-7", "Rodeo", "Trooper"],
  },
  {
    name: "Mazda",
    models: [
      "2",
      "3",
      "5",
      "6",
      "BT-50",
      "CX-3",
      "CX-5",
      "CX-7",
      "CX-9",
      "CX-30",
      "MX-5",
      "MPV",
      "Premacy",
    ],
  },
  {
    name: "Opel / Vauxhall",
    models: [
      "Adam",
      "Astra",
      "Cascada",
      "Combo",
      "Corsa",
      "Crossland",
      "Grandland",
      "Insignia",
      "Meriva",
      "Mokka",
      "Tigra",
      "Vectra",
      "Vivaro",
      "Zafira",
    ],
  },
  {
    name: "Fiat",
    models: [
      "500",
      "500X",
      "Bravo",
      "Doblo",
      "Ducato",
      "Freemont",
      "Grande Punto",
      "Linea",
      "Panda",
      "Punto",
      "Scudo",
      "Stilo",
      "Tipo",
    ],
  },
  {
    name: "Suzuki",
    models: [
      "Alto",
      "Baleno",
      "Celerio",
      "Grand Vitara",
      "Ignis",
      "Jimny",
      "Liana",
      "Splash",
      "Swift",
      "SX4",
      "Vitara",
      "Wagon R+",
    ],
  },
  {
    name: "Subaru",
    models: [
      "BRZ",
      "Forester",
      "Impreza",
      "Justy",
      "Legacy",
      "Levorg",
      "Outback",
      "Tribeca",
      "XV",
    ],
  },
  {
    name: "Lexus",
    models: ["CT", "ES", "GS", "GX", "IS", "LS", "LX", "NX", "RC", "RX", "UX"],
  },
  {
    name: "Infiniti",
    models: ["EX", "FX", "G", "JX", "M", "Q30", "Q50", "Q60", "QX"],
  },
  {
    name: "Acura",
    models: ["ILX", "MDX", "RDX", "RLX", "TLX"],
  },
  {
    name: "Volvo",
    models: [
      "S40",
      "S60",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC40",
      "XC60",
      "XC70",
      "XC90",
    ],
  },
  {
    name: "Porsche",
    models: ["718", "911", "Boxster", "Cayenne", "Cayman", "Macan", "Panamera"],
  },
  {
    name: "Tesla",
    models: ["Model 3", "Model S", "Model X", "Model Y"],
  },
  {
    name: "Dodge",
    models: [
      "Caliber",
      "Challenger",
      "Charger",
      "Dakota",
      "Durango",
      "Grand Caravan",
      "Journey",
      "Nitro",
      "Ram",
    ],
  },
  {
    name: "Chrysler",
    models: [
      "200",
      "300",
      "Grand Voyager",
      "Pacifica",
      "PT Cruiser",
      "Sebring",
    ],
  },
  {
    name: "Alfa Romeo",
    models: [
      "147",
      "156",
      "159",
      "Giulia",
      "Giulietta",
      "MiTo",
      "Spider",
      "Stelvio",
    ],
  },
  {
    name: "Seat",
    models: [
      "Alhambra",
      "Altea",
      "Arona",
      "Ateca",
      "Ibiza",
      "León",
      "Mii",
      "Tarraco",
      "Toledo",
    ],
  },
  {
    name: "Skoda",
    models: [
      "Fabia",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Rapid",
      "Roomster",
      "Superb",
      "Yeti",
    ],
  },
  {
    name: "Lada",
    models: ["Granta", "Kalina", "Largus", "Niva", "Priora", "Vesta"],
  },
  {
    name: "Chery",
    models: ["Arrizo", "Eastar", "QQ", "Tiggo", "Tiggo 2", "Tiggo 7"],
  },
  {
    name: "BYD",
    models: ["Atto 3", "Dolphin", "F3", "Han", "Song", "Tang"],
  },
  {
    name: "GAC",
    models: ["GS3", "GS4", "GS5", "GS7", "GS8"],
  },
  {
    name: "Great Wall",
    models: ["H6", "Hover", "Poer", "Wingle"],
  },
  {
    name: "Haval",
    models: ["H2", "H4", "H6", "H9", "Jolion"],
  },
  {
    name: "Geely",
    models: ["Atlas", "Coolray", "Emgrand", "MK", "Tugella"],
  },
  {
    name: "MG",
    models: ["MG3", "MG5", "MG6", "HS", "RX5", "ZS"],
  },
  {
    name: "SsangYong",
    models: ["Actyon", "Korando", "Musso", "Rexton", "Tivoli", "XLV"],
  },
  {
    name: "Daewoo",
    models: [
      "Espero",
      "Kalos",
      "Lacetti",
      "Lanos",
      "Matiz",
      "Nubira",
      "Tacuma",
    ],
  },
];

/** Liste des noms de marques triée alphabétiquement */
export const CAR_MAKES: string[] = CAR_DATA.map((m) => m.name).sort((a, b) =>
  a.localeCompare(b),
);

/** Modèles pour une marque donnée (insensible à la casse) */
export function getModelsForMake(makeName: string): string[] {
  const entry = CAR_DATA.find(
    (m) => m.name.toLowerCase() === makeName.toLowerCase(),
  );
  return entry?.models ?? [];
}

export const VEHICLE_COLORS: { value: string; label: string; hex: string }[] = [
  { value: "Blanc", label: "Blanc", hex: "#FFFFFF" },
  { value: "Noir", label: "Noir", hex: "#1a1a1a" },
  { value: "Gris", label: "Gris", hex: "#9ca3af" },
  { value: "Argent", label: "Argent", hex: "#d1d5db" },
  { value: "Rouge", label: "Rouge", hex: "#ef4444" },
  { value: "Bordeaux", label: "Bordeaux", hex: "#7f1d1d" },
  { value: "Bleu", label: "Bleu", hex: "#3b82f6" },
  { value: "Bleu nuit", label: "Bleu nuit", hex: "#1e3a5f" },
  { value: "Vert", label: "Vert", hex: "#22c55e" },
  { value: "Kaki", label: "Kaki", hex: "#78716c" },
  { value: "Beige", label: "Beige", hex: "#d4c5a9" },
  { value: "Marron", label: "Marron", hex: "#92400e" },
  { value: "Orange", label: "Orange", hex: "#f97316" },
  { value: "Jaune", label: "Jaune", hex: "#eab308" },
  { value: "Violet", label: "Violet", hex: "#8b5cf6" },
];
